spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
  #      data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist



mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

security:
  jwt:
    secret: bmZrc2RuZmtzZGZua3NkbmZramxkc2Zua2puc2tu
    access: 3600000
    refresh: 2592000000

springdoc:
  override-with-generic-response: false
